name: Python application

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m venv env
        env/bin/pip install --upgrade pip
        env/bin/pip install -r requirements.txt

    - name: Test application
      run: |
        env/bin/python -c "import pandas as pd"
